'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
!include ../../ApplicationApi/puml/KeypleCore-Api-ClassDiag-PlantUmlSetting.iuml

package org.eclipse.keyple.seproxy #FFFFFF {
  package event #FFFFFF {
    !include ../../ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_DEFAULTSELECTION_0_9_0
  }

  together {
    !include ../../ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_SELECTOR_0_9_0
    !include ../../ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_READER
    !include ../../ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_CHANNEL
  }

  package message #FFFFFF {
    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_DEFAULTSELECTION_0_9_0
    together {
      !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_PROXYREADER_0_9
      !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_SEREQUEST_0_9
      !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_APDUREQUEST_0_9
    }
    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_STATUS_0_9

    ProxyReader "1" -up- "+" SeRequest : sends >
    ProxyReader "1" -down-- "+" SeResponse : receives >
    SeRequest "1" o-right-> "*" ApduRequest : apduRequests
    SeResponse "0..1" o-right-> "*" ApduResponse : apduResponses
    SeResponse "1" o-down-> "0..1" SelectionStatus : selectionStatus
    SelectionStatus "1" o--> "0..1" ApduResponse : fci

    DefaultSelectionsRequest "1" -down-- "+" SeRequest : contains >
    DefaultSelectionsResponse "1" -up- "+" SeResponse : contains >
  }

  AbstractDefaultSelectionsRequest <|-right- DefaultSelectionsRequest : extends
  AbstractDefaultSelectionsResponse <|-right- DefaultSelectionsResponse : extends
  AbstractDefaultSelectionsRequest -down[hidden]------ AbstractDefaultSelectionsResponse

  SeSelector "0..1" <-right-o "1" SeRequest : selector
  SeReader <|-right- ProxyReader : extends
  ChannelControl "1" -- "1" ProxyReader : sets <

'  SeSelector -down[hidden]-- SeReader
'  SeReader -down[hidden]- ChannelControl

  SeSelector -down[hidden]- ChannelControl
  ChannelControl -down[hidden]-- SeReader


'  SeSelector -down[hidden]-- ChannelControl
  event -right[hidden]----- SeSelector
}
/'
    class SeRequest <<Serializable>>
    class SeResponse <<Serializable>>
    class ApduRequest <<Serializable>>
    class ApduResponse <<Serializable>>
    class SelectionStatus <<Serializable>>
'/

' Red
skinparam ClassBackgroundColor<<redL>> #FDEDEC
skinparam ClassBorderColor<<redB>> #E74C3C
'hide <<red>> stereotype

' Orange
skinparam ClassBackgroundColor<<orangeL>> #FDF2E9
skinparam ClassBorderColor<<orangeB>> #E67E22
'hide <<orange>> stereotype

class SeRequest <<Send>>
class ApduRequest <<Send>>
class DefaultSelectionsRequest <<Send>>
class SeSelector <<Send>>
class ChannelControl <<Send>>
hide <<Send>> stereotype

class SeResponse <<Receive>>
class ApduResponse <<Receive>>
class DefaultSelectionsResponse <<Receive>>
class SelectionStatus <<Receive>>
hide <<Receive>> stereotype

skinparam class {
  BackgroundColor<<Send>> #FDF2E9
  BorderColor<<Send>> #E67E22
  BackgroundColor<<Receive>> #FDEDEC
  BorderColor<<Receive>> #E74C3C
}


@enduml