'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
!include ../../Application/puml/KeypleCore-Api-ClassDiag-PlantUmlSetting.iuml

package org.eclipse.keyple.seproxy #FFFFFF {

  !include ../../Application/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_PLUGIN_0_9_COLOR
  !include ../../Application/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_READER_COLOR
  ReaderPlugin "1" *-right-> "*" SeReader : readers

  !include ../../Application/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_UTIL_0_9_0

  package message #FFFFFF {
    !include ../../SeChannel/puml/KeypleCore-SeChannelApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_PROXYREADER_0_9
  }

  ReaderPlugin -down-|> ProxyElement : extends
  SeReader -down-|> ProxyElement : extends

  SeReader <|-right- ProxyReader : extends

  package plugin #FFFFFF {
    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_CONFIGURABLE_0_9
    together {
      !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_PLUGIN_0_9
      !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_OBSERVALEPLUGIN_0_9
    }
    AbstractPlugin-right-|> AbstractSeProxyComponent : extends
'    AbstractPlugin <|-down-- AbstractThreadedObservablePlugin : extends
    AbstractPlugin <|-down- AbstractObservablePlugin : extends
    AbstractObservablePlugin <|-down- AbstractThreadedObservablePlugin : extends

    ProxyElement <|.down. AbstractSeProxyComponent : implements

    ReaderPlugin <|.. AbstractPlugin : implements
    ProxyReader <|.. AbstractReader : implements

    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_ABSTRACTREADER_0_9_0

    AbstractSeProxyComponent <|-right- AbstractReader : extends

    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_SMART_READER
    ProxyReader <|-- SmartSelectionReader : extends

'    package local #FFFFFF {
    together {
      !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_LOCALREADER_0_9_0
      !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_OBSERVABLEREADER_0_9_0

      AbstractObservableLocalReader -up-|> AbstractLocalReader: extends
    }
    AbstractReader <|-down- AbstractLocalReader : extends
    SmartSelectionReader-right[hidden]-> AbstractLocalReader
'    AbstractThreadedObservablePlugin -right[hidden]-> AbstractObservableLocalReader

    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_OBSERVABLE_NOTIFIER

'    AbstractObservablePlugin .down.|> ObservablePluginNotifier : implements
    AbstractObservablePlugin ..|> ObservablePluginNotifier : implements
    AbstractThreadedObservablePlugin -down[hidden]-> ObservablePluginNotifier
    AbstractObservableLocalReader .down.|> ObservableReaderNotifier : implements

    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!PLUGIN_SMART_OBSERVABLE
    ObservableReaderNotifier <|-left- SmartInsertionReader : extends
    ObservableReaderNotifier <|-right- SmartRemovalReader : extends
  }

  package event #FFFFFF {
    !include ../../Application/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_PLUGINOBSERVER_0_8_1
    !include ../../Application/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_OBSERVABLEPLUGIN_0_9_0
    !include ../../Application/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_OBSERVABLEREADER_0_9_0
    !include ../../Application/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_READEROBSERVER_0_8_1

'    ObservablePlugin -right[hidden]-> ObservableReader
    ObservablePlugin +-left- PluginObserver
    ObservablePlugin "1" o-- "*" PluginObserver : observes <

    ObservableReader +-right- ReaderObserver
    ObservableReader "1" o-- "*" ReaderObserver : observes <
  }

  ObservablePluginNotifier -down-|> ObservablePlugin : extends
  ObservableReaderNotifier -down-|> ObservableReader : extends

  ReaderPlugin <|-- ObservablePlugin : extends
  SeReader <|-- ObservableReader : extends
}
@enduml


