'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
!include ../../Application/puml/KeypleCore_Api_ClassDiag_PlantUmlSetting.iuml

package org.eclipse.keyple.seproxy #FFFFFF {
  together {
    !include ../../Application/puml/KeypleCore_SeProxy_ClassDiag_ClassElements.iuml!SEPROXY_READER_COLOR
    !include ../../Application/puml/KeypleCore_SeProxy_ClassDiag_ClassElements.iuml!SEPROXY_UTIL_0_9_COLOR
    !include ../../Application/puml/KeypleCore_SeProxy_ClassDiag_ClassElements.iuml!SEPROXY_PLUGIN_0_9_COLOR
  }
  package message #FFFFFF {
    !include ../../SeChannel/puml/KeypleCore_SeChannel_ClassDiag_ClassElements.iuml!MESSAGE_PROXYREADER_0_9
  }
  ReaderPlugin -right-|> ProxyElement : extends
  ProxyElement <|-right- SeReader : extends
  SeReader -down-> ProxyReader : extends

  package plugin #FFFFFF {
    together {
      !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_PLUGIN_0_9
      !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_OBSERVALEPLUGIN_0_9
      !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_OBSERVABLE_NOTIFIER
    }
    AbstractPlugin <|-down- AbstractObservablePlugin : extends
    AbstractObservablePlugin <|-down- AbstractThreadedObservablePlugin : extends
    AbstractThreadedObservablePlugin -down[hidden]-> ObservablePluginNotifier
    AbstractObservablePlugin ..|> ObservablePluginNotifier : implements

    package reader #FFFFFF {
      together {
        !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_ABSTRACTREADER_0_9_0
        class Toto
      }
      together {
        !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_LOCALREADER_0_9_0
        !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_SMART_READER
      }
      together {
        !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_OBSERVABLEREADER_0_9_0
        interface SmartInsertionReader
      }
      together {
        !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!READER_OBSERVABLE_NOTIFIER
        interface SmartRemovalReader
      }
      AbstractReader <|-down- AbstractLocalReader : extends
      AbstractLocalReader <|-down- AbstractObservableLocalReader : extends
      AbstractObservableLocalReader .down.|> ObservableReaderNotifier : implements
      Toto -down[hidden]- SmartSelectionReader
      SmartSelectionReader -down[hidden]- SmartInsertionReader
      SmartInsertionReader -down[hidden]- SmartRemovalReader
      hide Toto
      !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_SMART_OBSERVABLE

      SmartRemovalReader -right-|> ObservableReaderNotifier : extends
      ObservableReaderNotifier <|-- SmartInsertionReader : extends
    }
  }
  ReaderPlugin <|.down. AbstractPlugin : implements
  ProxyReader <|.down. AbstractReader : implements
  ProxyReader <|-- SmartSelectionReader : extends

  package event #FFFFFF {
    !include ../../Application/puml/KeypleCore_SeProxy_ClassDiag_ClassElements.iuml!SEPROXY_OBSERVABLEPLUGIN_0_9_0
    !include ../../Application/puml/KeypleCore_SeProxy_ClassDiag_ClassElements.iuml!SEPROXY_PLUGINOBSERVER_0_8_1
    ObservablePlugin +-right- PluginObserver
    ObservablePlugin "1" o-- "*" PluginObserver : observes <

    !include ../../Application/puml/KeypleCore_SeProxy_ClassDiag_ClassElements.iuml!SEPROXY_READEROBSERVER_0_8_1
    !include ../../Application/puml/KeypleCore_SeProxy_ClassDiag_ClassElements.iuml!SEPROXY_OBSERVABLEREADER_0_9_0
    ReaderObserver -right-+ ObservableReader
    ReaderObserver "*" --o "1" ObservableReader

    PluginObserver -right[hidden]-> ReaderObserver
  }
  ObservablePluginNotifier -down-|> ObservablePlugin : extends
  ObservableReaderNotifier -down-|> ObservableReader : extends

  ReaderPlugin <|-- ObservablePlugin : extends
  SeReader <|------------ ObservableReader : extends
}
@enduml
