'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml(id=PLUGIN_OBSERVABLE_NOTIFIER)
+interface ObservablePluginNotifier {
  +notifyObservers(<b>final</b> PluginEvent event)
}
@enduml

@startuml(id=READER_OBSERVABLE_NOTIFIER)
+interface ObservableReaderNotifier {
  +notifyObservers(<b>final</b> ReaderEvent event)
}
@enduml

@startuml(id=PLUGIN_OBSERVABLE_NOTIFIER_ReaderAPI)
+interface ObservableReaderNotifier {
  +notifyObservers(<b>final</b> ReaderEvent event)
}
@enduml

@startuml(id=PLUGIN_SMART_READER)
+interface SmartSelectionReader {
  +ApduResponse <color:blue>openChannelForAid</color>(AidSelector aidSelector)
}
@enduml

@startuml(id=PLUGIN_SMART_OBSERVABLE)
+interface SmartInsertionReader  {
  +boolean <color:blue>waitForCardPresent</color>()
  +<color:blue>stopWaitForCard</color>()
}

+interface SmartRemovalReader {
  +boolean <color:blue>waitForCardAbsentNative</color>()
  +<color:blue>stopWaitForCardRemoval</color>()
}
@enduml

@startuml(id=PLUGIN_CONFIGURABLE_0_8_1)
~abstract AbstractSeProxyComponent {
  -<b>final</b> String name
  --
  ~AbstractSeProxyComponent(String name)
  .. implements Nameable ..
  +<b>final</b> String getName()
  .. implements Configurable ..
  +<b>final</b> setParameters(Map<String, String> parameters)
}
@enduml

@startuml(id=PLUGIN_PLUGIN_0_8_1)
+abstract AbstractPlugin {
  #SortedSet<SeReader> readers

  #{abstract} SortedSet<SeReader> initNativeReaders()

  .. implements ReaderPlugin ..
  +<b>final</b> SortedSet<SeReader> getReaders()
  +<b>final</b> SortedSet<String> getReaderNames()
  +<b>final</b> SeReader getReader(String name)

  .. implements Comparable, fix in 0.9  ..
  +<b>final</b> int compareTo(ReadersPlugin o)
}
@enduml

@startuml(id=PLUGIN_PLUGIN_0_9)
+abstract AbstractPlugin {
  -<b>final</b> String name
  #ConcurrentMap<String, SeReader> readers
  --
  #{abstract} AbstractPlugin(String name)
'
  .. implementation of the package interface ProxyElement ..
  +<b>final</b> String getName()
  +<b>final</b> setParameters(Map<String, String> parameters)
'
  .. implementation of the public interface ReaderPlugin ..
  +<b>final</b> Set<String> getReaderNames()
  +<b>final</b> SeReader getReader(String name)
  +<b>final</b> ConcurrentMap<String, SeReader> getReaders()
'
  .. protected abstract method to be implemented by <color:blue>native</color> ReaderPlugin ..
  #{abstract} Map<String, SeReader> <color:blue>initNativeReaders</color>()
}
@enduml

@startuml(id=PLUGIN_OBSERVALEPLUGIN_0_8_1)
+abstract AbstractObservablePlugin {
  -List<PluginObserver> observers
  -<b>final</b> final Object sync
  --
  #AbstractObservablePlugin(String name)
'
  .. ObservablePlugin ..
  +addObserver(<b>final</b> PluginObserver observer)
  +removeObserver(<b>final</b> PluginObserver observer)
  +<b>final</b> notifyObservers(<b>final</b> PluginEvent event)
'
  .. To review - used by plugins Stub & Remote SE, to fix in 0.9 ..
  +clearObservers()
  +<b>final</b> int countObservers()
'
  .. To be implemented by native ObservablePlugin ..
  #{abstract} SortedSet<String> fetchNativeReadersNames()
  #{abstract} SeReader fetchNativeReader(String name)
'
  .. To review - used by unit test, to fix in 0.9 ..
  #Boolean isMonitoring()
}

+abstract AbstractThreadedObservablePlugin {
  -{static}<b>final</b> long SETTING_THREAD_TIMEOUT_DEFAULT
  -long threadWaitTimeout
  -<b>final</b> SortedSet<String> nativeReadersames
  -EventThread thread
  --
  #AbstractThreadedObservablePlugin(String name)
'
  .. To be implemented by native ObservablePlugin ..
  #{abstract} SortedSet<String> fetchNativeReadersNames()
  #{abstract} SeReader fetchNativeReader(String name)
'
  .. ObservablePlugin ..
  +<b>final</b> addObserver(PluginObserver observer)
  +<b>final</b> removeObserver(PluginObserver observer)
'
  .. To review - used by unit test, to fix in 0.9 ..
  #Boolean isMonitoring()
'
  .. To review - used by plugins Stub & Remote SE, to fix in 0.9 ..
  +<b>final</b> clearObservers()
}
@enduml

@startuml(id=PLUGIN_OBSERVALEPLUGIN_0_9)
+abstract AbstractObservablePlugin << <color:red>internal / dedicated</color> for RemoteSePlugin >>{
  -List<PluginObserver> observers
  -<b>final</b> final Object sync
  --
  #AbstractObservablePlugin(String name)
'
  .. implementation of the public interface ObservablePlugin ..
  +addObserver(<b>final</b> PluginObserver observer)
  +removeObserver(<b>final</b> PluginObserver observer)
  +clearObservers()
  +<b>final</b> int countObservers()

  .. implementation of the public interface ObservablePluginNotifier ..
  +<b>final</b> notifyObservers(<b>final</b> PluginEvent event)
}

+abstract AbstractThreadedObservablePlugin {
  -{static}<b>final</b> long SETTING_THREAD_TIMEOUT_DEFAULT
  -long threadWaitTimeout
  -<b>final</b> SortedSet<String> nativeReadersames
  -EventThread thread
  --
  #AbstractThreadedObservablePlugin(String name)
'
  .. Override of the implentation of the public interface ObservablePlugin ..
  +<b>final</b> addObserver(<b>final</b> PluginObserver observer)
  +<b>final</b> removeObserver(<b>final</b> PluginObserver observer)
  +<b>final</b> clearObservers()

  .. protected abstract methods to be implemented by <color:blue>native</color> ObservablePlugin ..
  #{abstract} SortedSet<String> <color:blue>fetchNativeReadersNames</color>()
  #{abstract} SeReader <color:blue>fetchNativeReader</color>(String name)
'
  .. internal process ..
  .. To review - used by unit test Stub & Remote SE ..
  #Boolean isMonitoring()
}
@enduml

@startuml(id=PLUGIN_ABSTRACTREADER_0_8_1)
+abstract AbstractReader {
  -<b>final</b> String pluginName
  #AbstractReader(String pluginName, String name)
  #<b>final</b> String getPluginName()

  .. implements ProxyReader ..
  +<b>final</b> List<SeResponse> transmitSet(Set<SeRequest requestSet, MultiSeRequestProcessing
    multiSeRequestProcessing, ChannelControl channelControl)
  +<b>final</b> List<SeResponse> transmitSet(Set<SeRequest requestSet)

  +<b>final</b> SeResponse transmit(SeRequest seRequest, ChannelControl channelControl)
  +<b>final</b> SeResponse transmit(SeRequest seRequest)

  .. To be implemented by AbstractLocalReader or VirtualReader ..
  #{abstract} List<SeResponse> processSeRequestSet(Set<SeRequest> requestSet,
    MultiSeRequestProcessing multiSeRequestProcessing, ChannelControl channelControl)
  #{abstract} SeResponse processSeRequest(SeRequest seRequest, ChannelControl channelControl)

  .. To review - implements Comparable, deprecated ..
  .. Will be defined as simple Set in 0.9  ..
  +<b>final</b> int compareTo(SeReader o)

  .. To review - to move to AbstractLocalReader or to AbstractObservableLocalReader, to fix in 0.9 ..
  #boolean forceClosing
}
@enduml

@startuml(id=PLUGIN_ABSTRACTREADER_0_9_0)
+abstract AbstractReader {
  -<b>final</b> String pluginName
  --
  #AbstractReader(String pluginName, String name)
  #<b>final</b> String getPluginName()
'
  .. implementation of the package interface ProxyElement ..
  +<b>final</b> String getName()
  +<b>final</b> setParameters(Map<String, String> parameters)
'
  .. implementation of tbe public interface ProxyReader ..
  +<b>final</b> List<SeResponse> transmitSeRequests(List<SeRequest seRequests, MultiSeRequestProcessing
    multiSeRequestProcessing, ChannelControl channelControl)

  +<b>final</b> SeResponse transmitSeRequest(SeRequest seRequest, ChannelControl channelControl)
'
  .. protected abstract methods to be implemented by AbstractLocalReader or VirtualReader ..
  #{abstract} List<SeResponse> processSeRequests(List<SeRequest> seRequests,
    MultiSeRequestProcessing multiSeRequestProcessing, ChannelControl channelControl)

  #{abstract} SeResponse processSeRequest(SeRequest seRequest, ChannelControl channelControl)
}
@enduml

@startuml(id=PLUGIN_LOCALREADER_0_8_1)
+abstract AbstractLocalReader {
  -{static}<b>final</b> byte[] getResponseHackRequestBytes
  -boolean logicalChannelIsOpen
  -SeSelector.AidSelector.IsoAid aidCurrentlySelected
  -SelectionStatus currentSelectionStatus
  -long before
  #Map<SeProtocol, String> protocolsMap
  --
  #AbstractLocalReader(String pluginName, String name)

  -ApduResponse recoverSelectionFciData(SeSelector.AidSelector aidSelector)
  -ApduResponse processExplicitAidSelection(SeSelector.AidSelector aidSelector)
  -SeResponse processSeRequestLogical(SeRequest seRequest)
  -ApduResponse processApduRequest(ApduRequest apduRequest)
  -ApduResponse case4HackGetResponse(int originalStatusCode)  #{abstract} byte[] getATR()

  .. implements SeReader ..
  +boolean isSePresent()
  +<b>final</b> addSeProtocolSetting(SeProtocol seProtocol, String protocolRule)
  +<b>final</b> setSeProtocols(Map<SeProtocol, String> seProtocolSettings)

  .. implements AbstractReader ..
  #<b>final</b> List<SeResponse> processSeRequestSet(Set<SeRequest> requestSet,
    MultiSeRequestProcessing multiSeRequestProcessing, ChannelControl channelControl)

  #<b>final</b> SeResponse processSeRequest(SeRequest seRequest, ChannelControl channelControl)

  .. To be implemented by native SeReader ..
  #{abstract} boolean checkSePresence()
  #{abstract} openPhysicalChannel()
  #{abstract} closePhysicalChannel()
  #{abstract} boolean isPhysicalChannelOpen()
  #{abstract} byte[] transmitApdu(byte[] apduIn)

  #{abstract} boolean protocolFlagMatches(SeProtocol protocolFlag)

  .. To review in 0.9 ..
  ~SelectionStatus openLogicalChannel(SeSelector seSelector)
  ~<b>final</b> SelectionStatus openLogicalChannelAndSelect(SeSelector seSelector)
  ~<b>final</b> boolean isLogicalChannelOpen()
  -closeLogicalChannel()
  #closeLogicalAndPhysicalChannels()
}
@enduml

@startuml(id=PLUGIN_LOCALREADER_0_9_0)
+abstract AbstractLocalReader {
  -{static}<b>final</b> byte[] getResponseHackRequestBytes
  -boolean logicalChannelIsOpen
  -SeSelector.AidSelector.IsoAid aidCurrentlySelected
  -SelectionStatus currentSelectionStatus
'  -long before
  -Map<SeProtocol, String> protocolsMap
  --
  #AbstractLocalReader(String pluginName, String name)'
  .. implementation of the public interface SeReader ..
  +<b>final</b> boolean isSePresent()
  +<b>final</b> addSeProtocolSetting(SeProtocol seProtocol, String protocolRule)
  +<b>final</b> setSeProtocols(Map<SeProtocol, String> seProtocolSettings)
'
  .. implementation of the protected abstract methods of the class AbstractReader ..
  #<b>final</b> List<SeResponse> processSeRequests(List<SeRequest> seRequests,
    MultiSeRequestProcessing multiSeRequestProcessing, ChannelControl channelControl)

  #<b>final</b> SeResponse processSeRequest(SeRequest seRequest, ChannelControl channelControl)
'
  .. protected abstract methods to be implemented by <color:blue>native</color> SeReader ..
  #{abstract} boolean <color:blue>protocolFlagMatches</color>(SeProtocol protocolFlag)
  #{abstract} boolean <color:blue>checkSePresence</color>()

  #{abstract} <color:blue>openPhysicalChannel</color>()
  #{abstract} <color:blue>closePhysicalChannel</color>()
  #{abstract} boolean <color:blue>isPhysicalChannelOpen</color>()

  #{abstract} byte[] <color:blue>getATR</color>()
  #{abstract} byte[] <color:blue>transmitApdu</color>(byte[] apduIn)
  .. internal process ..
  #<b>final</b> Map<SeProtocol, String> getProtocolsMap()

  -ApduResponse recoverSelectionFciData(SeSelector.AidSelector aidSelector)
  -ApduResponse processExplicitAidSelection(SeSelector.AidSelector aidSelector)
  -SeResponse processSeRequestLogical(SeRequest seRequest)
  -ApduResponse processApduRequest(ApduRequest apduRequest)
  -ApduResponse case4HackGetResponse(int originalStatusCode)

  ~SelectionStatus openLogicalChannel(SeSelector seSelector)
  ~<b>final</b> SelectionStatus openLogicalChannelAndSelect(SeSelector seSelector)
  ~<b>final</b> boolean isLogicalChannelOpen()
  -closeLogicalChannel()
  ~closeLogicalAndPhysicalChannels()
  ~{abstract} terminateSeCommunication()
}
@enduml

@startuml(id=PLUGIN_OBSERVABLEREADER_0_8_1)
+abstract AbstractObservableLocalReader {
  -DefaultSelectionsRequest[0..1] defaultSelectionsRequest
  -ObservableReader.NotificationMode notificationMode
  -ObservableReader.PollingMode currentPollingMode
  -ObservableReaderStateService stateService
  --
  #AbstractObservableLocalReader(String pluginName, String readerName)
  .. implements ObservableReader ..
  +<b>final</b> addObserver(ReaderObserver observer)
  +<b>final</b> removeObserver(ReaderObserver observer)

  +<b>final</b> notifyObservers(<b>final</b> ReaderEvent event)

  +<b>final</b> setDefaultSelectionRequest(AbstractDefaultSelectionsRequest selectionsR,
      NotificationMode notificationM, PollingMode[0..1] pollingM)

  +<b>final</b> startSeDetection(ObservableReader.PollingMode pollingMode)
  +<b>final</b> stopSeDetection()
  +<b>final</b> notifySeProcessed()
'
  .. To be implemented by native ObservableReader ..
  #{abstract} ObservableReaderStateService initStateService()

  .. To review - overrides SeReader from AbstractLocalReader, to fix in 0.9 ..
  +<b>final</b> boolean isSePresent()

  .. To review - access for the package state - to fix in 0.9 ..
  +<b>final</b> ReaderEvent processSeInserted()
  +<b>final</b> processSeRemoved()

  +ObservableReader.PollingMode getPollingMode()
  #switchState(AbstractObservableState.MonitoringState stateId)

  .. To review - access for unit test - to fix in 0.9 ..
  +AbstractObservableState.MonitoringState getCurrentMonitoringState()

  .. To review - access for the Android NFC plugin - to fix in 0.9 ..
  +onEvent(InternalEvent event)

  .. To review - access for AbstractLocalReader - to fix in 0.9 ..
  #startRemovalSequence()

  .. To review - used by Coppernic for not SmartRemoval, to fix in 0.9 ..
  +boolean isSePresentPing()
}
@enduml

@startuml(id=PLUGIN_OBSERVABLEREADER_0_9_0)
+abstract AbstractObservableLocalReader {
  -DefaultSelectionsRequest[0..1] defaultSelectionsRequest
  -ObservableReader.NotificationMode notificationMode
  -ObservableReader.PollingMode currentPollingMode
  -ObservableReaderStateService stateService
  --
  #AbstractObservableLocalReader(String pluginName, String readerName)
'
  .. implementation of the public interface ObservableReader ..
  +<b>final</b> addObserver(ReaderObserver observer)
  +<b>final</b> removeObserver(ReaderObserver observer)
  +<b>final</b> clearObservers()
  +<b>final</b> int countObservers()

  +<b>final</b> setDefaultSelectionRequest(AbstractDefaultSelectionsRequest selectionsR,
      NotificationMode notificationM, PollingMode[0..1] pollingM)

  +<b>final</b> startSeDetection(ObservableReader.PollingMode pollingMode)
  +<b>final</b> stopSeDetection()
  +<b>final</b> finalizeSeProcessing()
'
  .. implementation the public interface ObservableReaderNotifier ..
  +<b>final</b> notifyObservers(<b>final</b> ReaderEvent event)
'
  .. protected abstract method to be implemented by <color:blue>native</color> ObservableReader ..
  #{abstract} ObservableReaderStateService <color:blue>initStateService</color>()

  .. internal process ..
  .. protected method that could be overridden by <color:blue>native</color> not thread-based ..
  .. ObservableReader in Core API 0.9 => will be hidden in version 1.0 ..
  #<color:blue>onEvent</color>(InternalEvent event)
'

  ~terminateSeCommunication()

  ~startRemovalSequence()
  ~<b>final</b> ReaderEvent processSeInserted()
  ~<b>final</b> processSeRemoved()
  ~ObservableReader.PollingMode getPollingMode()
  ~switchState(AbstractObservableState.MonitoringState stateId)
  ~AbstractObservableState.MonitoringState getCurrentMonitoringState()
  ~boolean isSePresentPing()
}
@enduml

@startuml(id=PLUGIN_POOLPLUGIN_0_9_0)
+abstract AbstractPoolPlugin {
  #AbstractPoolPlugin(String name)
}
@enduml